export enum IconValues {
  PAYMENT_LINK = 'link',
  TERMINAL = 'payment',
  HELPCIRCLE = 'help-circle',
  REJECTED = 'error',
  SUCCESSFUL = 'success',
  FILTER = 'filter',
  SEARCH = 'search',
  BANCOLOMBIA = 'bancolombia',
  NEQUI = 'nequi',
  CARD = 'card',
  DAVIPLATA = 'daviplata',
  PSE = 'pse',
  VISA = 'visa',
}
